### ISSUE TITLE
2-Step Verification

### ISSUE THREAD

**Issue by regmebaby** [shellscape/Gmail-Notifier-Plus#139]
Will the Notifier continue to work when a user enables Google's "2-Step Verification"?
[https://www.google.com/landing/2step/](https://www.google.com/landing/2step/)

Does anyone have experiences on that topic?

**Comment by shellscape** [comment]
@jansokoly is the present active maintainer. Hopefully he'll have an answer for you.

**Comment by jansokoly** [comment]
@regmebaby it will. Just [generate an App Password](https://support.google.com/accounts/answer/185833?hl=en) and use it when connecting an account.

**Comment by regmebaby** [comment]
I just switched to _2-Step Verification_. _App Password_ works fine. Thanks!
