### ISSUE TITLE
High DPI enhancements of .NET 4.7 broke the layout

### ISSUE THREAD

**Issue by jansokoly** [shellscape/Gmail-Notifier-Plus#142]
Windows 10 Creators Updates includes .NET 4.7, which introduced [enhancements to high DPI and dynamic DPI support in Windows Forms](https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms).
For some reason, these changes have obviously broken layout of GNP. Investigation needed.

![image](https://user-images.githubusercontent.com/69093/27191358-d588aa7e-51f7-11e7-9d67-7f229aace3b4.png)

**Comment by jansokoly** [comment]
Looks like Patch Tuesday fixed it again. And it even looks crisper than ever.

**Comment by shellscape** [comment]
Great news! I'm positive everyone appreciates you keeping tabs on it.
