### ISSUE TITLE
Firefox instead of Chrome

### ISSUE THREAD

**Issue by seaquake** [shellscape/Gmail-Notifier-Plus#144]
Hi,
thanks for this great app.

My default browser is Chrome, but when i click on your app it open gmail on Firefox.

Is there a way to change the default browser inside your app?

Thanks for support.

**Comment by pneuschwander** [comment]
@seaquake Yes there is. That setting is account specific. Go to settings and edit your account. Then you can see the setting "Browser" :)

**Comment by seaquake** [comment]
Thanks a lot.
